"""
Generated alert types — produced by security analysis, not user input.
"""


class AlertType:
    POSSIBLE_BRUTE_FORCE = "POSSIBLE_BRUTE_FORCE"
    EXCESSIVE_FAILED_LOGINS = "EXCESSIVE_FAILED_LOGINS"
    REPEATED_PERMISSION_DENIED = "REPEATED_PERMISSION_DENIED"
    SUSPICIOUS_AUTH_BEHAVIOR = "SUSPICIOUS_AUTH_BEHAVIOR"
    EXCESSIVE_API_USAGE = "EXCESSIVE_API_USAGE"
    HIGH_SEVERITY_EVENT = "HIGH_SEVERITY_EVENT"
